### ISSUE TITLE
Can we get releases/tags?

### ISSUE THREAD

**Issue by tankerkiller125** [yiisoft/cookies#13]
I'm part of the [Flarum](https://flarum.org) software project and we are currently looking at replacing our existing cookie library because it lacks PHP 8.0 support and because it hasn't been updated properly in at least 2 years. This library appears to be the perfect replacement, however because it lacks tags/releases we are unable to use it.

Is there any chance that tags/releases could be done for this library so that other projects can use it properly without warnings about stability and other issues?

**Comment by samdark** [comment]
Yes. I plan to tag it soon. Did a cleanup not that long ago and was waiting for other team members feedback in case there's anything wrong with public API. Got no issue reports so far. Did you have a chance to review the code? If so and you've found no issues, I'll tag 1.0.0.

**Comment by tankerkiller125** [comment]
I've forced it into our project as a test (local branch), and I found zero issues during both manual testing as well as our automated testing infrastructure. Looking through the code itself for a bit I found no glaring issues that have any cause for concern for me.

**Comment by samdark** [comment]
We actually use 7.4 typed properties. That's the minimum version for Yii 3 family of packages.

PHP 7.2 will stop receiving security patches in 2 days. PHP 7.3 will be gone in a year: https://www.php.net/supported-versions.php. Supporting too many versions may become a huge pain due to [PHPUnit versioning policy](https://phpunit.de/supported-versions.html). If you want 8.0, you can't have 7.2 etc., and there backwards incompatible changes between major versions. We [support 5.3+ for Yii 1](https://github.com/yiisoft/yii/actions/runs/387637260) but with [a way that is quite hacky](https://github.com/yiisoft/phpunit-patches).

**Comment by samdark** [comment]
Tagged 1.0.0.
